spring:
  application:
    name: department-service
#  config:
#    import: "optional:configserver:http://localhost:8088"



server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}